# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-31 15:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_auto_20180131_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_creator', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_following', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
