# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-05 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('user_auth', '0010_auto_20180203_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rooms',
            field=models.ManyToManyField(to='chat.Room'),
        ),
    ]
