# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-21 15:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0011_user_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rooms',
        ),
        migrations.AddField(
            model_name='user',
            name='thumbnail',
            field=models.ImageField(blank=True, default=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='friends',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
