# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-27 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0013_auto_20180224_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default_user.jpeg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default_user.jpeg', upload_to=''),
        ),
    ]
