# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-09 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20180208_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceroom',
            name='label',
            field=models.SlugField(),
        ),
    ]
