# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-09 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20180210_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceroom',
            name='label',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='directroom',
            name='label',
            field=models.TextField(),
        ),
    ]
