# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-13 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20180210_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceroom',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='directroom',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
