# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-16 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20180214_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceroom',
            name='key',
            field=models.CharField(default=1, max_length=60),
        ),
    ]
